name: streamly
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  http: ^1.1.0
  get_it: ^7.6.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  go_router: ^12.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  image_picker: ^1.1.2
  flutter_screenutil: ^5.9.3
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  equatable: ^2.0.7
  flutter_staggered_grid_view: ^0.7.0
  rating_and_feedback_collector: ^0.0.3
  flutter_otp_text_field: ^1.1.0+2
  dotted_border: ^2.1.0
  pin_code_fields: ^8.0.1
  signature: ^6.0.0
  flutter_svg: ^2.1.0
  smooth_page_indicator: ^1.2.1
  video_player: ^2.9.5
  chewie: ^1.11.3
  better_player_plus: ^1.0.8
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  mobile_scanner: ^6.0.7
  speech_to_text: ^7.0.0
  flutter_rating: ^2.0.2
  carousel_slider: ^5.0.0
  dio: ^5.8.0+1
  path_provider: ^2.1.5
  flutter_downloader: ^1.12.0
  google_mlkit_text_recognition: ^0.15.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter_icons:
      android: true
      ios: true
      image_path: "assets/launcher_icon/stremly.png"


flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/launcher_icon/
    - assets/data/content.json

  #   - images/a_dot_ham.jpeg


#  fonts:
#    - family: Menseal
#      fonts:
#        - asset: assets/fonts/Menseal-Regular.ttf

